---
version: '3.8'
volumes:
  jackett_config: {}
  redis_data: {}

services:
  annatar:
    image: docker.io/mikmc/annatar:latest
    ports:
      - "8000:8000"
    depends_on:
      - jackett
    volumes:
      - "redis_data:/app/data"
    environment:
      LOG_LEVEL: debug
      JACKETT_URL: "https://mik25-jackett.elfhosted.com"
      JACKETT_API_KEY: "5xh2exon8sa9upaadr8s69jxywtko9s8"
      JACKETT_MAX_RESULTS: "100" # max results from jackett search
      JACKETT_TIMEOUT: "60" # max time spent searching per indexer.
      JACKETT_INDEXERS: "btsow,cinemageddon,fearnopeer,hdforever,knaben,laidbackmanor,milkie,ncore,onlyencodes-api,privatehd,skipthecommercials-api,skipthetrailers,solidtorrents,torlock,torrentdownloads,torrenting,totheglorycookie"
      LISTEN_PORT: "8000"

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
